### ISSUE TITLE
Return full message from GitHub 

### ISSUE THREAD

**Issue by vincentsarago** [mapbox/hookshot#3]
First, this is really awesome! 

Just a quick note, returning a shortened version of the message is good in the case when you want to subscribe for a `Push` event, but I think it could be useful to return the full message if the user (me) want to subscribe to other event other than Push.

cc @rclark

**Comment by rclark** [comment]
This implementation accepts the webhook from Github, validates that it came from github, and then forwards the event to your lambda function via SNS message. The problem is that there's a limit on the acceptable size of an SNS message, and Github messages for particularly gnarly commits / prs can surpass that limit.

There's also a PR #2 that would do nothing more than set up the API gateway resources and send the webhooks directly to your lambda function. Downside there is that the authentication isn't done for you. 

One approach to consider:
- Make this library `module.exports` a function for validating the payload from the webhook
- Merge #2 
- If you want to listen to non-push events, you could use the passthrough webhook from #2 and then in your own lambda code utilize the payload validation script?

Another approach might be to drop the SNS middleman and have the validation function make a `lambda.invoke()` request. The downside there is that there's no baked-in-retry on direct lambda invocations.

**Comment by rclark** [comment]
This is solved by the new `.passthrough()` function.
